---
- name: Copy configuration files
  hosts: all
  gather_facts: no

  tasks:
    - name: nginx config file
      template: src=../config/nginx.conf dest=/etc/nginx/sites-enabled/cv
      register: nginx_config
    - name: nginx restart
      service: name=nginx state=restarted
      when: nginx_config.changed
    
